project_id = "cycthtodyhyssfirdrzh"

[auth]
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.send-verification-email]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
